# Generated by Django 5.2.3 on 2025-07-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_alter_post_categoryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryname',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
