# Generated by Django 5.2.3 on 2025-07-03 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_category_post_categoryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryname',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='theblog.category'),
        ),
    ]
