# Generated by Django 5.2.3 on 2025-07-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_alter_post_categoryname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoryname',
            new_name='category',
        ),
    ]
