# Generated by Django 5.2.3 on 2025-07-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_alter_post_author_alter_post_snippet_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagramlink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='websitelink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
